"""initial

Revision ID: 3258c497c91d
Revises: 
Create Date: 2021-10-25 23:00:43.614044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3258c497c91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costumer')
    op.drop_table('advertising_team')
    op.drop_table('target')
    op.drop_table('advertiser')
    op.drop_table('advertising_campaign')
    op.drop_table('environment')
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('environment',
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_media', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('costumer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertising_campaign',
    sa.Column('campaign_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('environment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertiser',
    sa.Column('advertiser_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('advertiser_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('target',
    sa.Column('target_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age_group', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intrest_group', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('target_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertising_team',
    sa.Column('team_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertiser_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('costumer',
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('costumer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
