"""empty message

Revision ID: e3469326d4d8
Revises: 9b5203f0935d
Create Date: 2021-11-02 00:56:43.004931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3469326d4d8'
down_revision = '9b5203f0935d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('iq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'iq')
    # ### end Alembic commands ###
