"""empty message

Revision ID: ec85d1ea6ec6
Revises: 3258c497c91d
Create Date: 2021-11-02 00:50:17.233833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec85d1ea6ec6'
down_revision = '3258c497c91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('professor_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('GPA', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.professor_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('course_student',
    sa.Column('course_student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('course_student_id')
    )
    op.create_table('join_request',
    sa.Column('join_request_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('join_request_id')
    )
    op.drop_table('environment')
    op.drop_table('costumer')
    op.drop_table('payment')
    op.drop_table('advertising_team')
    op.drop_table('target')
    op.drop_table('advertiser')
    op.drop_table('advertising_campaign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_campaign',
    sa.Column('campaign_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('environment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertiser',
    sa.Column('advertiser_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('advertiser_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('target',
    sa.Column('target_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('age_group', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intrest_group', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('target_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('advertising_team',
    sa.Column('team_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertiser_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('costumer',
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('costumer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('environment',
    sa.Column('costumer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_media', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('costumer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('join_request')
    op.drop_table('course_student')
    op.drop_table('course')
    op.drop_table('student')
    op.drop_table('professor')
    # ### end Alembic commands ###
